export type ScriptedChatMessage = {
  id: string;
  offsetSeconds: number;
  authorName: string;
  authorRole: string;
  authorCity: string;
  message: string;
  kind: 'scripted_user' | 'agent_question';
  isSynthetic: true;
  videoBlock: string;
};

export const SCRIPTED_CHAT_MESSAGES: ScriptedChatMessage[] = [
  {
    id: 'ambient_001',
    offsetSeconds: 2,
    authorName: 'Марина',
    authorRole: 'юрист',
    authorCity: 'Москва',
    message: 'Добрый день всем!',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Старт эфира',
  },
  {
    id: 'ambient_002',
    offsetSeconds: 5,
    authorName: 'Игорь',
    authorRole: 'адвокат',
    authorCity: 'Казань',
    message: 'Здравствуйте, коллеги.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Старт эфира',
  },
  {
    id: 'ambient_003',
    offsetSeconds: 8,
    authorName: 'Елена',
    authorRole: 'налоговый консультант',
    authorCity: 'Екатеринбург',
    message: 'Привет из Екатеринбурга, тема очень актуальная.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Старт эфира',
  },
  {
    id: 'ambient_004',
    offsetSeconds: 12,
    authorName: 'Дмитрий',
    authorRole: 'юрист',
    authorCity: 'Новосибирск',
    message: 'На связи, Новосибирск. Интересно про клиентов с долгами.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Старт эфира',
  },
  {
    id: 'agent_q01',
    offsetSeconds: 90,
    authorName: 'Дмитрий',
    authorRole: 'юрист',
    authorCity: 'Новосибирск',
    message:
      'А если клиент уже консультировался у другого юриста и ушел - это потерянный клиент или его еще можно вернуть?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Проблема потери клиента',
  },
  {
    id: 'ambient_005',
    offsetSeconds: 128,
    authorName: 'Ольга',
    authorRole: 'юрист',
    authorCity: 'Ростов-на-Дону',
    message: 'Узнаваемо, у меня так же было в прошлом месяце.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Проблема потери клиента',
  },
  {
    id: 'ambient_006',
    offsetSeconds: 210,
    authorName: 'Наталья',
    authorRole: 'юрист',
    authorCity: 'Краснодар',
    message: 'Часто клиент приходит уже в панике, когда счета заблокированы.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Сигналы долгового клиента',
  },
  {
    id: 'agent_q02',
    offsetSeconds: 285,
    authorName: 'Елена',
    authorRole: 'налоговый консультант',
    authorCity: 'Екатеринбург',
    message: 'Если у клиента уже блокировка счета по налогам, это тоже тот самый сигнал, или это другая история?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Сигналы долгового клиента',
  },
  {
    id: 'ambient_007',
    offsetSeconds: 338,
    authorName: 'Сергей',
    authorRole: 'арбитражный юрист',
    authorCity: 'Пермь',
    message: '+1 к вопросу, очень актуально.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Сигналы долгового клиента',
  },
  {
    id: 'ambient_008',
    offsetSeconds: 420,
    authorName: 'Виктор',
    authorRole: 'арбитражный управляющий',
    authorCity: 'Воронеж',
    message: 'Важно, что клиенту нельзя обещать результат без диагностики документов.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Безопасная коммуникация',
  },
  {
    id: 'agent_q03',
    offsetSeconds: 495,
    authorName: 'Антон',
    authorRole: 'финансовый консультант',
    authorCity: 'Самара',
    message:
      'Как корректно говорить с клиентом, чтобы не обещать ему результат? Был случай: ожидания завысили, потом пришлось объяснять.',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Безопасная коммуникация',
  },
  {
    id: 'ambient_009',
    offsetSeconds: 575,
    authorName: 'Ирина',
    authorRole: 'налоговый консультант',
    authorCity: 'Воронеж',
    message: 'Фраза про диагностику звучит спокойнее, чем сразу говорить про банкротство.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Диагностика вместо давления',
  },
  {
    id: 'ambient_010',
    offsetSeconds: 660,
    authorName: 'Павел',
    authorRole: 'адвокат',
    authorCity: 'Красноярск',
    message: 'У меня клиенты часто боятся суда, хотя проблема уже давно не решается переговорами.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Диагностика вместо давления',
  },
  {
    id: 'agent_q04',
    offsetSeconds: 750,
    authorName: 'Ольга',
    authorRole: 'юрист',
    authorCity: 'Ростов-на-Дону',
    message: 'Правильно понимаю, что документы, суд и кредиторов берет на себя АСПБ, а партнер не ведет процедуру сам?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Что берет на себя АСПБ',
  },
  {
    id: 'ambient_011',
    offsetSeconds: 835,
    authorName: 'Алексей',
    authorRole: 'корпоративный юрист',
    authorCity: 'Нижний Новгород',
    message: 'Для корпоративных клиентов это особенно важно: им нужен понятный маршрут, а не общая консультация.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Что берет на себя АСПБ',
  },
  {
    id: 'ambient_012',
    offsetSeconds: 930,
    authorName: 'Марина',
    authorRole: 'юрист',
    authorCity: 'Москва',
    message: 'Согласна, партнеру важно не превращаться в операционного исполнителя по банкротству.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Роль партнера',
  },
  {
    id: 'agent_q05',
    offsetSeconds: 1035,
    authorName: 'Наталья',
    authorRole: 'юрист',
    authorCity: 'Краснодар',
    message:
      'Если я не хочу сама вести банкротство, но вижу у клиента долговую проблему, это как раз формат передачи в АСПБ?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Роль партнера',
  },
  {
    id: 'ambient_013',
    offsetSeconds: 1135,
    authorName: 'Татьяна',
    authorRole: 'финансовый консультант',
    authorCity: 'Тюмень',
    message: 'Хорошо, что можно не перестраивать всю практику, а просто добавить понятный маршрут.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Роль партнера',
  },
  {
    id: 'ambient_014',
    offsetSeconds: 1245,
    authorName: 'Сергей',
    authorRole: 'арбитражный юрист',
    authorCity: 'Пермь',
    message: 'Про кредиторов узнаваемо. Обычно клиент тянет до последнего.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Когда передавать клиента',
  },
  {
    id: 'agent_q06',
    offsetSeconds: 1395,
    authorName: 'Ирина',
    authorRole: 'налоговый консультант',
    authorCity: 'Воронеж',
    message:
      'Если уже есть ФНС, кредиторы и просроченные налоги, где граница: еще консультируем сами или пора передавать дальше?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Когда передавать клиента',
  },
  {
    id: 'ambient_015',
    offsetSeconds: 1510,
    authorName: 'Виктор',
    authorRole: 'арбитражный управляющий',
    authorCity: 'Воронеж',
    message: 'В таких кейсах ранняя диагностика часто экономит клиенту месяцы хаоса.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Когда передавать клиента',
  },
  {
    id: 'ambient_016',
    offsetSeconds: 1635,
    authorName: 'Игорь',
    authorRole: 'адвокат',
    authorCity: 'Казань',
    message: 'Интересно, как это работает для ИП, там ведь часто смешаны личные и бизнес-долги.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Типы клиентов',
  },
  {
    id: 'agent_q07',
    offsetSeconds: 1755,
    authorName: 'Игорь',
    authorRole: 'адвокат',
    authorCity: 'Казань',
    message: 'Если клиент ИП, маршрут отличается от юрлица или сначала все равно нужна диагностика документов?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Типы клиентов',
  },
  {
    id: 'ambient_017',
    offsetSeconds: 1880,
    authorName: 'Павел',
    authorRole: 'адвокат',
    authorCity: 'Красноярск',
    message: 'У ИП это частый вопрос, потому что клиент думает, что бизнес-долги отдельно от него.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Типы клиентов',
  },
  {
    id: 'ambient_018',
    offsetSeconds: 1995,
    authorName: 'Алексей',
    authorRole: 'корпоративный юрист',
    authorCity: 'Нижний Новгород',
    message: 'Про договор важно. Без фиксации условий потом сложно объяснить, откуда пришел клиент.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Партнерская модель',
  },
  {
    id: 'agent_q08',
    offsetSeconds: 2115,
    authorName: 'Марина',
    authorRole: 'юрист',
    authorCity: 'Москва',
    message: 'Партнерские условия фиксируются договором сразу или после первого переданного клиента?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Партнерская модель',
  },
  {
    id: 'ambient_019',
    offsetSeconds: 2240,
    authorName: 'Татьяна',
    authorRole: 'финансовый консультант',
    authorCity: 'Тюмень',
    message: 'Мне нравится, что нет устных договоренностей. Для партнерства это критично.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Партнерская модель',
  },
  {
    id: 'ambient_020',
    offsetSeconds: 2360,
    authorName: 'Елена',
    authorRole: 'налоговый консультант',
    authorCity: 'Екатеринбург',
    message: 'Вспомнила клиента: налоги, поставщики, кассовый разрыв, а он все еще надеется "перетерпеть".',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Кейсы участников',
  },
  {
    id: 'agent_q09',
    offsetSeconds: 2475,
    authorName: 'Сергей',
    authorRole: 'арбитражный юрист',
    authorCity: 'Пермь',
    message: 'Если у клиента сразу долги, кредиторы и просроченные налоги, с чего правильно начинать разбор?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Кейсы участников',
  },
  {
    id: 'ambient_021',
    offsetSeconds: 2595,
    authorName: 'Дмитрий',
    authorRole: 'юрист',
    authorCity: 'Новосибирск',
    message: 'Такие кейсы обычно и приходят на консультацию, но без команды дальше сложно.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Кейсы участников',
  },
  {
    id: 'ambient_022',
    offsetSeconds: 2720,
    authorName: 'Наталья',
    authorRole: 'юрист',
    authorCity: 'Краснодар',
    message: 'Уже понятно, кому из моих клиентов это можно предложить без давления.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Финальный шаг',
  },
  {
    id: 'agent_q10',
    offsetSeconds: 2955,
    authorName: 'Алексей',
    authorRole: 'корпоративный юрист',
    authorCity: 'Нижний Новгород',
    message:
      'После эфира лучше сразу оставлять заявку или сначала собрать список клиентов, которых потенциально можно передать?',
    kind: 'agent_question',
    isSynthetic: true,
    videoBlock: 'Финальный шаг',
  },
  {
    id: 'ambient_023',
    offsetSeconds: 3045,
    authorName: 'Антон',
    authorRole: 'финансовый консультант',
    authorCity: 'Самара',
    message: 'После эфира оставлю заявку, хочу понять формат передачи клиентов.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Финальный шаг',
  },
  {
    id: 'ambient_024',
    offsetSeconds: 3120,
    authorName: 'Ирина',
    authorRole: 'налоговый консультант',
    authorCity: 'Воронеж',
    message: 'Хочу обсудить пару налоговых кейсов, где уже есть риск банкротства.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Финальный шаг',
  },
  {
    id: 'ambient_025',
    offsetSeconds: 3180,
    authorName: 'Виктор',
    authorRole: 'арбитражный управляющий',
    authorCity: 'Воронеж',
    message: 'Спасибо, структура партнерства понятная.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Финальный шаг',
  },
  {
    id: 'ambient_026',
    offsetSeconds: 3240,
    authorName: 'Ольга',
    authorRole: 'юрист',
    authorCity: 'Ростов-на-Дону',
    message: 'Спасибо за эфир, очень полезно!',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Завершение',
  },
  {
    id: 'ambient_027',
    offsetSeconds: 3260,
    authorName: 'Марина',
    authorRole: 'юрист',
    authorCity: 'Москва',
    message: 'Иду оставлять заявку.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Завершение',
  },
  {
    id: 'ambient_028',
    offsetSeconds: 3270,
    authorName: 'Игорь',
    authorRole: 'адвокат',
    authorCity: 'Казань',
    message: 'Отличный вебинар, спасибо команде АСПБ.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Завершение',
  },
  {
    id: 'ambient_029',
    offsetSeconds: 255,
    authorName: 'Татьяна',
    authorRole: 'финансовый консультант',
    authorCity: 'Тюмень',
    message: 'У клиентов часто нет понимания, что проблему можно разобрать законно, без паники.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Сигналы долгового клиента',
  },
  {
    id: 'ambient_030',
    offsetSeconds: 610,
    authorName: 'Алексей',
    authorRole: 'корпоративный юрист',
    authorCity: 'Нижний Новгород',
    message: 'Хороший акцент: сначала документы и диагностика, потом уже маршрут.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Безопасная коммуникация',
  },
  {
    id: 'ambient_031',
    offsetSeconds: 980,
    authorName: 'Павел',
    authorRole: 'адвокат',
    authorCity: 'Красноярск',
    message: 'Для адвокатов это удобный формат: не вести всю процедуру, но не бросать клиента.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Роль партнера',
  },
  {
    id: 'ambient_032',
    offsetSeconds: 1320,
    authorName: 'Марина',
    authorRole: 'юрист',
    authorCity: 'Москва',
    message: 'Кажется, такой сценарий особенно хорошо зайдет для повторных клиентов.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Когда передавать клиента',
  },
  {
    id: 'ambient_033',
    offsetSeconds: 1695,
    authorName: 'Наталья',
    authorRole: 'юрист',
    authorCity: 'Краснодар',
    message: 'У меня как раз есть ИП с личными поручительствами, нужно будет обсудить.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Типы клиентов',
  },
  {
    id: 'ambient_034',
    offsetSeconds: 2045,
    authorName: 'Виктор',
    authorRole: 'арбитражный управляющий',
    authorCity: 'Воронеж',
    message: 'Документальная фиксация партнерства сильно снижает риск недопонимания.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Партнерская модель',
  },
  {
    id: 'ambient_035',
    offsetSeconds: 2865,
    authorName: 'Елена',
    authorRole: 'налоговый консультант',
    authorCity: 'Екатеринбург',
    message: 'Уже понятно, какие кейсы можно принести на диагностику первыми.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Финальный шаг',
  },
  {
    id: 'ambient_036',
    offsetSeconds: 3285,
    authorName: 'Татьяна',
    authorRole: 'финансовый консультант',
    authorCity: 'Тюмень',
    message: 'Коллеги, всем спасибо, было полезно.',
    kind: 'scripted_user',
    isSynthetic: true,
    videoBlock: 'Завершение',
  },
];

export function getScriptedChatMessagesUntil(offsetSeconds: number) {
  return SCRIPTED_CHAT_MESSAGES.filter(message => message.offsetSeconds <= offsetSeconds);
}
