/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './crisis_premium/**/*.html',
    './crisis_premium/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#bcc7dd',
        'on-tertiary-fixed-variant': '#3c475a',
        'background': '#f8f9fa',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'secondary-fixed': '#ffdea5',
        'on-secondary-fixed': '#261900',
        'primary-fixed': '#d2e4fb',
        'on-secondary-fixed-variant': '#5d4201',
        'surface-container': '#edeeef',
        'on-tertiary-fixed': '#111c2c',
        'on-surface': '#191c1d',
        'on-secondary': '#ffffff',
        'surface': '#f8f9fa',
        'on-error-container': '#93000a',
        'inverse-primary': '#b7c8de',
        'secondary-fixed-dim': '#e9c176',
        'outline': '#74777d',
        'surface-tint': '#4f6073',
        'primary': '#041627',
        'on-primary-container': '#8192a7',
        'surface-dim': '#d9dadb',
        'surface-container-high': '#e7e8e9',
        'on-primary-fixed-variant': '#38485a',
        'on-background': '#191c1d',
        'tertiary-fixed': '#d8e3fa',
        'on-primary-fixed': '#0b1d2d',
        'outline-variant': '#c4c6cd',
        'surface-variant': '#e1e3e4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1f2a3b',
        'surface-bright': '#f8f9fa',
        'secondary': '#775a19',
        'inverse-surface': '#2e3132',
        'surface-container-low': '#f3f4f5',
        'surface-container-highest': '#e1e3e4',
        'primary-fixed-dim': '#b7c8de',
        'on-secondary-container': '#785a1a',
        'secondary-container': '#fed488',
        'error': '#ba1a1a',
        'tertiary': '#0a1526',
        'on-surface-variant': '#44474c',
        'primary-container': '#1a2b3c',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#8691a6',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max-width': '1280px',
        'margin-desktop': '48px',
        unit: '4px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Manrope'],
        'body-lg': ['Manrope'],
        'headline-xl': ['Manrope'],
        'headline-lg': ['Manrope'],
        'headline-sm': ['Manrope'],
        'headline-md': ['Manrope'],
        'label-sm': ['Manrope'],
        'label-md': ['Manrope'],
        'body-md': ['Manrope'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
